# Generated by Django 4.2.6 on 2023-12-07 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0004_transactionlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionlog',
            options={'ordering': ('-timestamp',), 'verbose_name': 'Transaction Log', 'verbose_name_plural': 'Transaction Logs'},
        ),
        migrations.RemoveField(
            model_name='transactionlog',
            name='action',
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='transaction_type',
            field=models.CharField(choices=[('POINTS_SPENT', 'Points Spent'), ('POINTS_RECEIVED', 'Points Received'), ('BIDS_USED', 'Bids Used'), ('BIDS_RECEIVED', 'Bids Received')], default=django.utils.timezone.now, max_length=20, verbose_name='Transaction Type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
