# Generated by Django 4.2.6 on 2023-12-16 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_transactionlog_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='no_bid',
            new_name='nb_bid',
        ),
    ]
