# Generated by Django 4.2.6 on 2024-01-02 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0007_rename_no_bid_bid_nb_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
