# Generated by Django 4.2.6 on 2024-01-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_alter_transactionlog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlog',
            name='username',
            field=models.CharField(blank=True, max_length=200, verbose_name='Username'),
        ),
    ]
