# Generated by Django 4.2.6 on 2023-11-10 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatroom_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified Date'),
        ),
    ]
