# Generated by Django 4.2.6 on 2023-12-04 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0042_alter_project_saved_by_users'),
        ('chat', '0007_alter_chatroom_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
    ]
