# Generated by Django 4.2.6 on 2023-12-04 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0042_alter_project_saved_by_users'),
        ('chat', '0008_alter_chatroom_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='project',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.project'),
        ),
    ]
