# Generated by Django 4.2.6 on 2023-12-18 09:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_alter_message_chat_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Message'),
            preserve_default=False,
        ),
    ]
