# Generated by Django 4.2.6 on 2023-12-24 13:06

import chat.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_messagereceiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='files',
            field=models.FileField(default=django.utils.timezone.now, upload_to=chat.models.Message.project_chat_file_path, verbose_name='File'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.BinaryField(),
        ),
    ]
