# Generated by Django 4.2.6 on 2023-12-24 13:36

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_message_files_alter_message_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='files',
        ),
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(upload_to=chat.models.Message.project_chat_file_path, verbose_name='File'),
        ),
    ]
