# Generated by Django 4.2.6 on 2023-12-27 20:47

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_rename_message_message_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(null=True, upload_to=chat.models.Message.project_chat_file_path, verbose_name='File'),
        ),
    ]
