# Generated by Django 4.2.6 on 2023-11-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_resume', '0002_workphoto_userpreviouswork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workphoto',
            name='photo',
            field=models.ImageField(upload_to='profile/<django.db.models.query_utils.DeferredAttribute object at 0x00000197ED496410>/wp/<django.db.models.query_utils.DeferredAttribute object at 0x00000197ED4AE550>/%y-%m-%d'),
        ),
    ]
