# Generated by Django 4.2.6 on 2023-11-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_resume', '0003_alter_workphoto_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workphoto',
            name='photo',
            field=models.ImageField(upload_to='profile/<django.db.models.query_utils.DeferredAttribute object at 0x00000190073F67D0>/wp/<django.db.models.query_utils.DeferredAttribute object at 0x0000019007183950>/%y-%m-%d'),
        ),
    ]
