# Generated by Django 4.2.6 on 2023-11-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_resume', '0004_alter_workphoto_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workphoto',
            name='photo',
            field=models.ImageField(upload_to='profile/<django.db.models.query_utils.DeferredAttribute object at 0x000002259D256510>/wp/<django.db.models.query_utils.DeferredAttribute object at 0x000002259D26E990>/%y-%m-%d'),
        ),
    ]
