# Generated by Django 4.2.6 on 2023-11-24 08:33

from django.db import migrations, models
import django.db.models.deletion
import user_resume.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_resume', '0005_alter_workphoto_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreviouswork',
            name='photos',
        ),
        migrations.AddField(
            model_name='workphoto',
            name='previous_work',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='user_resume.userpreviouswork'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workphoto',
            name='photo',
            field=models.ImageField(upload_to=user_resume.models.PortfolioFile.portfolio_file_upload_path),
        ),
    ]
