# Generated by Django 4.2.6 on 2023-11-24 09:25

from django.db import migrations, models
import user_resume.models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
        ('user_resume', '0006_remove_userpreviouswork_photos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreviouswork',
            name='description',
            field=models.TextField(default=1, verbose_name='Work Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpreviouswork',
            name='sample',
            field=models.TextField(blank=True, verbose_name='Work Sample'),
        ),
        migrations.AddField(
            model_name='userpreviouswork',
            name='skills',
            field=models.ManyToManyField(related_name='user_skills', to='user_resume.userskill'),
        ),
        migrations.AddField(
            model_name='userpreviouswork',
            name='work_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('code', 'Code'), ('article', 'Article'), ('other', 'Other')], default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userskill',
            name='skills',
            field=models.ManyToManyField(related_name='user_skills', to='education.skill'),
        ),
        migrations.AlterField(
            model_name='workphoto',
            name='photo',
            field=models.FileField(upload_to=user_resume.models.PortfolioFile.portfolio_file_upload_path),
        ),
    ]
