# Generated by Django 4.2.6 on 2023-11-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
        ('user_resume', '0007_userpreviouswork_description_userpreviouswork_sample_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreviouswork',
            name='skills',
            field=models.ManyToManyField(related_name='work_skills', to='education.skill'),
        ),
    ]
