# Generated by Django 4.2.6 on 2023-11-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_resume', '0008_alter_userpreviouswork_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreviouswork',
            name='work_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('code', 'Code'), ('article', 'Article'), ('others', 'Others')], max_length=40),
        ),
    ]
