# Generated by Django 4.2.6 on 2023-11-24 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_resume', '0010_workfile_delete_workphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreviouswork',
            name='skills',
        ),
    ]
