# Generated by Django 4.2.6 on 2023-11-24 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_resume', '0011_remove_userpreviouswork_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workfile',
            name='previous_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prev_work_file', to='user_resume.userpreviouswork'),
        ),
    ]
