# Generated by Django 4.2.6 on 2023-11-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
        ('user_resume', '0012_alter_workfile_previous_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreviouswork',
            name='skills',
            field=models.ManyToManyField(related_name='work_skills', to='education.skill'),
        ),
    ]
