# Generated by Django 4.2.6 on 2023-11-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_resume', '0013_userpreviouswork_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreviouswork',
            name='skills',
            field=models.ManyToManyField(related_name='work_skills', to='user_resume.userskill'),
        ),
    ]
