# Generated by Django 4.2.6 on 2023-11-27 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
        ('user_resume', '0014_alter_userpreviouswork_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userskill',
            name='skills',
        ),
        migrations.AddField(
            model_name='userskill',
            name='skills',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to='education.skill'),
            preserve_default=False,
        ),
    ]
