# Generated by Django 4.2.6 on 2023-11-27 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education', '0002_remove_skill_description_alter_degree_name_and_more'),
        ('user_resume', '0017_remove_userskill_skills_alter_userskill_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userskill',
            name='skills',
        ),
        migrations.AlterField(
            model_name='userskill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userskill',
            name='skills',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to='education.skill'),
            preserve_default=False,
        ),
    ]
