# Generated by Django 4.2.6 on 2023-11-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_remove_skill_description_alter_degree_name_and_more'),
        ('user_resume', '0019_remove_userskill_skills_alter_userskill_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreviouswork',
            name='skills',
            field=models.ManyToManyField(related_name='work_skills', to='education.skill'),
        ),
    ]
