# Generated by Django 4.2.6 on 2023-11-27 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user_resume.models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_remove_skill_description_alter_degree_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_resume', '0020_alter_userpreviouswork_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=user_resume.models.PortfolioFile.portfolio_file_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='UserPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('code', 'Code'), ('article', 'Article'), ('others', 'Others')], max_length=40)),
                ('title', models.CharField(max_length=200, verbose_name='Work Title')),
                ('description', models.TextField(verbose_name='Work Description')),
                ('sample', models.TextField(blank=True, verbose_name='Work Sample')),
                ('skills', models.ManyToManyField(related_name='work_skills', to='education.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_portfolio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='workfile',
            name='previous_work',
        ),
        migrations.DeleteModel(
            name='UserPreviousWork',
        ),
        migrations.DeleteModel(
            name='WorkFile',
        ),
        migrations.AddField(
            model_name='portfoliofile',
            name='portfolio_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_file', to='user_resume.userportfolio'),
        ),
    ]
