# Generated by Django 4.2.6 on 2023-11-27 13:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import user_resume.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education', '0002_remove_skill_description_alter_degree_name_and_more'),
        ('user_resume', '0021_portfoliofile_userportfolio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfoliofile',
            options={'verbose_name': 'Portfolio File', 'verbose_name_plural': 'Portfolio Files'},
        ),
        migrations.AlterModelOptions(
            name='usereducation',
            options={'verbose_name': 'User Education', 'verbose_name_plural': 'User Educations'},
        ),
        migrations.AlterModelOptions(
            name='userportfolio',
            options={'verbose_name': 'User Portfolio', 'verbose_name_plural': 'User Portfolios'},
        ),
        migrations.AlterModelOptions(
            name='userreview',
            options={'verbose_name': 'User Review', 'verbose_name_plural': 'User Reviews'},
        ),
        migrations.AlterModelOptions(
            name='userskill',
            options={'verbose_name': 'User Skill', 'verbose_name_plural': 'User Skills'},
        ),
        migrations.AlterField(
            model_name='portfoliofile',
            name='file',
            field=models.FileField(upload_to=user_resume.models.PortfolioFile.portfolio_file_upload_path, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='usereducation',
            name='degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_degrees', to='education.degree', verbose_name='Degree'),
        ),
        migrations.AlterField(
            model_name='usereducation',
            name='end_date',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='usereducation',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_majors', to='education.major', verbose_name='Major'),
        ),
        migrations.AlterField(
            model_name='usereducation',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='usereducation',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_universities', to='education.university', verbose_name='University'),
        ),
        migrations.AlterField(
            model_name='userportfolio',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Work Title'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='reviewed_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews_received', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed User'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews_given', to=settings.AUTH_USER_MODEL, verbose_name='Reviewer'),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='skills',
            field=models.ManyToManyField(related_name='user_skills', to='education.skill', verbose_name='Skills'),
        ),
        migrations.CreateModel(
            name='UserExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Experience Title')),
                ('company_name', models.CharField(max_length=100, verbose_name='Experience Company Name')),
                ('position', models.CharField(max_length=100, verbose_name='Experience Position')),
                ('start_date', models.DateField(verbose_name='Experience Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Experience End Date')),
                ('description', models.TextField(verbose_name='Description')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_experience', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Work Experience',
                'verbose_name_plural': 'Work Experiences',
                'ordering': ['-start_date'],
            },
        ),
    ]
