# Generated by Django 4.2.6 on 2023-11-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_resume', '0022_alter_portfoliofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexperience',
            name='present',
            field=models.BooleanField(default=False, verbose_name='I am currently working in this position'),
        ),
        migrations.AlterField(
            model_name='userexperience',
            name='company_name',
            field=models.CharField(max_length=100, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='userexperience',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='userexperience',
            name='position',
            field=models.CharField(max_length=100, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='userexperience',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='userexperience',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
