# Generated by Django 4.2.6 on 2023-11-27 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0037_alter_chosenproposal_options_alter_project_options_and_more'),
        ('user_resume', '0023_userexperience_present_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='project_reviews', to='project.project'),
            preserve_default=False,
        ),
    ]
