# Generated by Django 4.2.6 on 2023-11-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_resume', '0024_userreview_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='title',
            field=models.CharField(choices=[('client', 'Client'), ('freelancer', 'Freelancer')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
