# Generated by Django 4.2.6 on 2023-11-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_resume', '0029_alter_userreview_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreview',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Created At'),
        ),
    ]
