# Generated by Django 4.2.6 on 2023-12-01 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_resume', '0031_usersavedproject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSavedProject',
        ),
    ]
