# Generated by Django 4.2.6 on 2023-12-04 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_resume', '0036_userstatistics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserStatistics',
        ),
    ]
