# Generated by Django 4.2.6 on 2023-12-04 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0040_project_saved_by_users'),
        ('user_resume', '0037_delete_userstatistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.project')),
                ('proposals', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.chosenproposal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_statistic', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
