# Generated by Django 4.2.6 on 2023-12-04 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_resume', '0040_alter_userstatistics_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatistics',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_statistic', to=settings.AUTH_USER_MODEL),
        ),
    ]
