# Generated by Django 4.2.6 on 2023-12-04 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0042_alter_project_saved_by_users'),
        ('user_resume', '0041_alter_userstatistics_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreview',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_reviews', to='project.project'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='reviewed_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviews_received', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed User'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviews_given', to=settings.AUTH_USER_MODEL, verbose_name='Reviewer'),
        ),
    ]
