# Generated by Django 4.2.6 on 2023-12-04 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_resume', '0043_alter_userreview_project_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userstatistics',
            options={'verbose_name': 'User Statistics', 'verbose_name_plural': 'User Statistics'},
        ),
    ]
