# Generated by Django 4.2.6 on 2024-01-02 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_resume', '0044_alter_userstatistics_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userexperience',
            options={'ordering': ['-start_date'], 'verbose_name': 'User Work Experience', 'verbose_name_plural': 'User Work Experiences'},
        ),
        migrations.AlterModelOptions(
            name='usersavedproject',
            options={'ordering': ['-saved_time'], 'verbose_name': 'User Project Saved', 'verbose_name_plural': 'User Projects saved'},
        ),
    ]
