# Generated by Django 4.2.6 on 2024-01-02 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_resume', '0046_alter_usersavedproject_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usersavedproject',
            table=None,
        ),
    ]
