# Generated by Django 4.2.6 on 2024-01-02 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_resume', '0048_rename_usersavedproject_sssss'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sssss',
        ),
    ]
