# Generated by Django 4.2.6 on 2024-01-02 12:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0052_remove_project_saved_by_users'),
        ('user_resume', '0050_sssss'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sssss',
            new_name='UserSavedProject',
        ),
    ]
