# Generated by Django 4.2.6 on 2023-11-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Project Title')),
                ('description', models.TextField(verbose_name='Project description')),
                ('additional_notes', models.CharField(blank=True, max_length=200, verbose_name='Additional Notes')),
                ('due_date', models.DateTimeField(verbose_name='Due Date')),
                ('file', models.FileField(upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('skill_needed', models.ManyToManyField(related_name='project_needed', to='education.skill')),
            ],
        ),
    ]
