# Generated by Django 4.2.6 on 2023-11-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_published_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='due_date',
            field=models.DateField(verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
