# Generated by Django 4.2.6 on 2023-11-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_multipleupload_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='files',
        ),
        migrations.AddField(
            model_name='project',
            name='files',
            field=models.ManyToManyField(blank=True, null=True, related_name='project_files', to='project.multipleupload'),
        ),
    ]
