# Generated by Django 4.2.6 on 2023-11-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_remove_project_files_project_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='project_files', to='project.multipleupload'),
        ),
    ]
