# Generated by Django 4.2.6 on 2023-11-03 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0009_projectfile_remove_project_files_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='max_price',
            field=models.DecimalField(decimal_places=2, default=1.2, max_digits=10, verbose_name='Maximum Price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=1.1, max_digits=10, verbose_name='Minimum Price'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_files', to='project.project'),
        ),
        migrations.CreateModel(
            name='ProjectProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_text', models.TextField(verbose_name='Proposal Text')),
                ('proposed_price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Proposed Price')),
                ('submission_date', models.DateTimeField(verbose_name='Submission Date')),
                ('proposal_date', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_proposals', to='project.project')),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_proposals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChosenProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chosen_proposals', to='project.project')),
                ('selected_proposal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_for_project', to='project.projectproposal')),
            ],
        ),
    ]
