# Generated by Django 4.2.6 on 2023-11-03 11:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_project_max_price_project_min_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chosenproposal',
            name='chosen_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
