# Generated by Django 4.2.6 on 2023-11-03 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0016_alter_project_max_price_alter_project_min_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chosenproposal',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chosen_proposals', to='project.project'),
        ),
        migrations.AlterField(
            model_name='chosenproposal',
            name='selected_proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_for_project', to='project.projectproposal'),
        ),
        migrations.AlterUniqueTogether(
            name='projectproposal',
            unique_together={('project', 'proposer')},
        ),
    ]
