# Generated by Django 4.2.6 on 2023-11-03 12:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_alter_chosenproposal_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectproposal',
            name='proposed_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(5.0)], verbose_name='Proposed Price'),
        ),
    ]
