# Generated by Django 4.2.6 on 2023-11-03 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_alter_projectproposal_proposed_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chosenproposal',
            unique_together={('project', 'selected_proposal')},
        ),
    ]
