# Generated by Django 4.2.6 on 2023-11-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_alter_chosenproposal_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
