# Generated by Django 4.2.6 on 2023-11-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0029_remove_chosenproposal_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='has_selected_proposal',
            field=models.BooleanField(default=False),
        ),
    ]
