# Generated by Django 4.2.6 on 2023-11-06 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0031_project_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='has_selected_proposal',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_active',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
