# Generated by Django 4.2.6 on 2023-11-06 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0033_alter_project_status_projectcommunication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectCommunication',
        ),
    ]
