# Generated by Django 4.2.6 on 2023-11-27 13:10

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0036_alter_project_max_price_alter_project_min_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chosenproposal',
            options={'verbose_name': 'Chosen Proposal', 'verbose_name_plural': 'Chosen Proposals'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='projectfile',
            options={'verbose_name': 'Project File', 'verbose_name_plural': 'Project Files'},
        ),
        migrations.AlterModelOptions(
            name='projectproposal',
            options={'verbose_name': 'Project Proposal', 'verbose_name_plural': 'Project Proposals'},
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='file',
            field=models.FileField(upload_to=project.models.ProjectFile.project_file_path, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At'),
        ),
    ]
