# Generated by Django 4.2.6 on 2023-12-01 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0038_alter_project_max_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='max_price',
            field=models.IntegerField(verbose_name='Maximum Price'),
        ),
        migrations.AlterField(
            model_name='project',
            name='min_price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(10)], verbose_name='Minimum Price'),
        ),
    ]
