# Generated by Django 4.2.6 on 2023-12-02 19:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0039_alter_project_max_price_alter_project_min_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='saved_by_users',
            field=models.ManyToManyField(related_name='user_saved_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
