# Generated by Django 4.2.6 on 2023-12-04 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0042_alter_project_saved_by_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chosenproposal',
            name='project',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.project'),
        ),
        migrations.AlterField(
            model_name='chosenproposal',
            name='selected_proposal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_projects', to='project.projectproposal'),
        ),
        migrations.AlterField(
            model_name='project',
            name='published_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_files', to='project.project'),
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_proposals', to='project.project'),
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='proposer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_proposals', to=settings.AUTH_USER_MODEL),
        ),
    ]
