# Generated by Django 4.2.6 on 2023-12-05 08:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0046_alter_projectproposal_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='proposal_time_end',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Proposal Time End'),
            preserve_default=False,
        ),
    ]
