# Generated by Django 4.2.6 on 2023-12-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0047_project_proposal_time_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='proposal_time_end',
            field=models.DateField(verbose_name='Proposal Time End'),
        ),
    ]
