# Generated by Django 4.2.6 on 2023-12-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0048_alter_project_proposal_time_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectproposal',
            name='is_price_adjusted',
            field=models.BooleanField(default=False, verbose_name='Adjust Price'),
        ),
    ]
