# Generated by Django 4.2.6 on 2024-01-02 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0051_alter_project_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='saved_by_users',
        ),
    ]
