# Generated by Django 4.2.6 on 2024-01-02 12:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_resume', '0051_rename_sssss_usersavedproject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0052_remove_project_saved_by_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='saved_by_users',
            field=models.ManyToManyField(blank=True, related_name='user_saved_projects', through='user_resume.UserSavedProject', to=settings.AUTH_USER_MODEL),
        ),
    ]
