# Generated by Django 4.2.6 on 2024-01-02 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0053_project_saved_by_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='saved_by_users',
        ),
    ]
