# Generated by Django 4.2.6 on 2024-01-08 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0055_alter_project_published_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='published_username',
            field=models.CharField(blank=True, max_length=200, verbose_name='Published Username'),
        ),
        migrations.AlterField(
            model_name='project',
            name='published_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
