# Generated by Django 4.2.6 on 2024-01-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0056_project_published_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectproposal',
            name='proposer_username',
            field=models.CharField(blank=True, max_length=200, verbose_name='Proposer Username'),
        ),
    ]
