# Generated by Django 4.2.6 on 2024-01-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0059_remove_chosenproposal_project_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectproposal',
            name='is_canceled',
            field=models.BooleanField(default=False, verbose_name='Canceled'),
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='Accepted'),
        ),
    ]
