# Generated by Django 4.2.6 on 2024-01-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0060_projectproposal_is_canceled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chosenproposal',
            name='is_canceled',
            field=models.BooleanField(default=False, verbose_name='Canceled'),
        ),
        migrations.AlterField(
            model_name='chosenproposal',
            name='chosen_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Chosen Date'),
        ),
    ]
