# Generated by Django 4.2.6 on 2024-01-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0063_dispute'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='opened_by_username',
            field=models.CharField(blank=True, max_length=200, verbose_name='Opened By Username'),
        ),
    ]
