# Generated by Django 4.2.6 on 2024-01-16 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0065_chosenproposal_selected_proposal_d'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chosenproposal',
            name='selected_proposal_d',
        ),
    ]
