# Generated by Django 4.2.6 on 2023-11-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='new_email_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='New Email Verification'),
        ),
    ]
