# Generated by Django 4.2.6 on 2023-11-02 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_new_email_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreview',
            name='reviewed_user',
        ),
        migrations.RemoveField(
            model_name='userreview',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='userskill',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='userskill',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserEducation',
        ),
        migrations.DeleteModel(
            name='UserReview',
        ),
        migrations.DeleteModel(
            name='UserSkill',
        ),
    ]
