# Generated by Django 4.2.6 on 2023-11-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_userreview_reviewed_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='new_email_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='New Email Verification'),
        ),
    ]
