# Generated by Django 4.2.6 on 2023-11-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_new_email_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile/<django.db.models.query_utils.DeferredAttribute object at 0x00000197ED496410>/cp/%y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='pp.jpeg', upload_to='profile/<django.db.models.query_utils.DeferredAttribute object at 0x00000197ED496410>/pp/%y-%m-%d'),
        ),
    ]
