# Generated by Django 4.2.6 on 2023-11-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_userprofile_cover_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile/<django.db.models.query_utils.DeferredAttribute object at 0x00000190073F67D0>/cp/%y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='pp.jpeg', max_length=200, upload_to='profile/<django.db.models.query_utils.DeferredAttribute object at 0x00000190073F67D0>/pp/%y-%m-%d'),
        ),
    ]
