# Generated by Django 4.2.6 on 2023-11-24 07:58

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_userprofile_cover_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.UserProfile.cover_photo_upload_path),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='pp.jpeg', upload_to=user.models.UserProfile.profile_picture_upload_path),
        ),
    ]
