# Generated by Django 4.2.6 on 2023-11-27 13:10

from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('user', '0008_alter_userprofile_cover_photo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.UserProfile.cover_photo_upload_path, verbose_name='Cover Photo'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_locations', to='location.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nationality',
            field=models.ManyToManyField(blank=True, related_name='user_nationalities', to='location.nationality', verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='pp.jpeg', upload_to=user.models.UserProfile.profile_picture_upload_path, verbose_name='Profile Picture'),
        ),
    ]
