# Generated by Django 4.2.6 on 2023-12-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_user_tfa_enabled_user_tfa_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tfa_enabled',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tfa_secret',
        ),
        migrations.AddField(
            model_name='user',
            name='otp_auth_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_base32',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
