# Generated by Django 4.2.6 on 2023-12-12 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_remove_user_tfa_enabled_remove_user_tfa_secret_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp_verified',
        ),
    ]
