# Generated by Django 4.2.6 on 2023-12-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_delete_tokenmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verification_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='primary_verification_method',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('OTP', 'One-Time Password')], default='EMAIL', max_length=10, verbose_name='Verification Method'),
        ),
    ]
