# Generated by Django 4.2.6 on 2023-12-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_user_primary_verification_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='primary_verification_method',
            field=models.CharField(choices=[('NONE', 'None'), ('EMAIL', 'Email'), ('OTP', 'One-Time Password')], default='NONE', max_length=10, verbose_name='Verification Method'),
        ),
    ]
