# Generated by Django 4.2.6 on 2023-12-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_user_primary_verification_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_auth_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_base32',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
