# Generated by Django 4.2.6 on 2023-12-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_alter_user_otp_auth_url_alter_user_otp_base32'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_base32',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
