# Generated by Django 4.2.6 on 2023-12-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_alter_user_otp_auth_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_base32',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email Base32'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verification_enabled',
            field=models.BooleanField(default=False, verbose_name='2fa Email Status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_auth_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='OTP Authentication URL'),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_base32',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='OTP Base32'),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_enabled',
            field=models.BooleanField(default=False, verbose_name='2fa OTP Status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='primary_verification_method',
            field=models.CharField(blank=True, choices=[('EMAIL', 'Email'), ('OTP', 'One-Time Password')], max_length=10, null=True, verbose_name='Verification Method'),
        ),
    ]
