# Generated by Django 4.2.6 on 2023-12-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_alter_user_email_base32_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='backup_enabled',
            field=models.BooleanField(default=False, verbose_name='2fa Backup Status'),
        ),
        migrations.AddField(
            model_name='user',
            name='backup_tokens',
            field=models.TextField(blank=True, null=True, verbose_name='Backup Tokens'),
        ),
    ]
